# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NinjaApiSheets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import NinjaApiContracts_pb2 as NinjaApiContracts__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='NinjaApiSheets.proto',
  package='NinjaApiMessages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14NinjaApiSheets.proto\x12\x10NinjaApiMessages\x1a\x17NinjaApiContracts.proto\"`\n\tGetSheets\x12\x33\n\x04type\x18\x01 \x01(\x0e\x32%.NinjaApiMessages.GetSheets.SheetType\"\x1e\n\tSheetType\x12\x11\n\rFUTURE_SHEETS\x10\x00\"U\n\x05Sheet\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12-\n\tcontracts\x18\x03 \x03(\x0b\x32\x1a.NinjaApiMessages.Contract\"1\n\x06Sheets\x12\'\n\x06sheets\x18\x01 \x03(\x0b\x32\x17.NinjaApiMessages.Sheet\"\x1e\n\x0cGetSheetRisk\x12\x0e\n\x06sheets\x18\x01 \x03(\t\"S\n\tSheetRisk\x12\r\n\x05sheet\x18\x01 \x01(\t\x12\x10\n\x08\x63lipSize\x18\x02 \x01(\r\x12\x12\n\nordersSent\x18\x03 \x01(\r\x12\x11\n\tmaxOrders\x18\x04 \x01(\r\"C\n\rSheetRiskList\x12\x32\n\rriskForSheets\x18\x01 \x03(\x0b\x32\x1b.NinjaApiMessages.SheetRisk\" \n\x0eGetSheetStates\x12\x0e\n\x06sheets\x18\x01 \x03(\t\"y\n\nSheetState\x12\r\n\x05sheet\x18\x01 \x01(\t\x12\x33\n\x06status\x18\x02 \x01(\x0e\x32#.NinjaApiMessages.SheetState.Status\"\'\n\x06Status\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\x07\n\x03OFF\x10\x01\x12\x06\n\x02ON\x10\x02\"@\n\x0bSheetStates\x12\x31\n\x0bsheetStates\x18\x01 \x03(\x0b\x32\x1c.NinjaApiMessages.SheetStateb\x06proto3'
  ,
  dependencies=[NinjaApiContracts__pb2.DESCRIPTOR,])



_GETSHEETS_SHEETTYPE = _descriptor.EnumDescriptor(
  name='SheetType',
  full_name='NinjaApiMessages.GetSheets.SheetType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FUTURE_SHEETS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=133,
  serialized_end=163,
)
_sym_db.RegisterEnumDescriptor(_GETSHEETS_SHEETTYPE)

_SHEETSTATE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='NinjaApiMessages.SheetState.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISABLED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ON', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=605,
  serialized_end=644,
)
_sym_db.RegisterEnumDescriptor(_SHEETSTATE_STATUS)


_GETSHEETS = _descriptor.Descriptor(
  name='GetSheets',
  full_name='NinjaApiMessages.GetSheets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='NinjaApiMessages.GetSheets.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETSHEETS_SHEETTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=163,
)


_SHEET = _descriptor.Descriptor(
  name='Sheet',
  full_name='NinjaApiMessages.Sheet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NinjaApiMessages.Sheet.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account', full_name='NinjaApiMessages.Sheet.account', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contracts', full_name='NinjaApiMessages.Sheet.contracts', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=250,
)


_SHEETS = _descriptor.Descriptor(
  name='Sheets',
  full_name='NinjaApiMessages.Sheets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sheets', full_name='NinjaApiMessages.Sheets.sheets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=301,
)


_GETSHEETRISK = _descriptor.Descriptor(
  name='GetSheetRisk',
  full_name='NinjaApiMessages.GetSheetRisk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sheets', full_name='NinjaApiMessages.GetSheetRisk.sheets', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=333,
)


_SHEETRISK = _descriptor.Descriptor(
  name='SheetRisk',
  full_name='NinjaApiMessages.SheetRisk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sheet', full_name='NinjaApiMessages.SheetRisk.sheet', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clipSize', full_name='NinjaApiMessages.SheetRisk.clipSize', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ordersSent', full_name='NinjaApiMessages.SheetRisk.ordersSent', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxOrders', full_name='NinjaApiMessages.SheetRisk.maxOrders', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=418,
)


_SHEETRISKLIST = _descriptor.Descriptor(
  name='SheetRiskList',
  full_name='NinjaApiMessages.SheetRiskList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='riskForSheets', full_name='NinjaApiMessages.SheetRiskList.riskForSheets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=487,
)


_GETSHEETSTATES = _descriptor.Descriptor(
  name='GetSheetStates',
  full_name='NinjaApiMessages.GetSheetStates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sheets', full_name='NinjaApiMessages.GetSheetStates.sheets', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=521,
)


_SHEETSTATE = _descriptor.Descriptor(
  name='SheetState',
  full_name='NinjaApiMessages.SheetState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sheet', full_name='NinjaApiMessages.SheetState.sheet', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='NinjaApiMessages.SheetState.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SHEETSTATE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=644,
)


_SHEETSTATES = _descriptor.Descriptor(
  name='SheetStates',
  full_name='NinjaApiMessages.SheetStates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sheetStates', full_name='NinjaApiMessages.SheetStates.sheetStates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=646,
  serialized_end=710,
)

_GETSHEETS.fields_by_name['type'].enum_type = _GETSHEETS_SHEETTYPE
_GETSHEETS_SHEETTYPE.containing_type = _GETSHEETS
_SHEET.fields_by_name['contracts'].message_type = NinjaApiContracts__pb2._CONTRACT
_SHEETS.fields_by_name['sheets'].message_type = _SHEET
_SHEETRISKLIST.fields_by_name['riskForSheets'].message_type = _SHEETRISK
_SHEETSTATE.fields_by_name['status'].enum_type = _SHEETSTATE_STATUS
_SHEETSTATE_STATUS.containing_type = _SHEETSTATE
_SHEETSTATES.fields_by_name['sheetStates'].message_type = _SHEETSTATE
DESCRIPTOR.message_types_by_name['GetSheets'] = _GETSHEETS
DESCRIPTOR.message_types_by_name['Sheet'] = _SHEET
DESCRIPTOR.message_types_by_name['Sheets'] = _SHEETS
DESCRIPTOR.message_types_by_name['GetSheetRisk'] = _GETSHEETRISK
DESCRIPTOR.message_types_by_name['SheetRisk'] = _SHEETRISK
DESCRIPTOR.message_types_by_name['SheetRiskList'] = _SHEETRISKLIST
DESCRIPTOR.message_types_by_name['GetSheetStates'] = _GETSHEETSTATES
DESCRIPTOR.message_types_by_name['SheetState'] = _SHEETSTATE
DESCRIPTOR.message_types_by_name['SheetStates'] = _SHEETSTATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSheets = _reflection.GeneratedProtocolMessageType('GetSheets', (_message.Message,), {
  'DESCRIPTOR' : _GETSHEETS,
  '__module__' : 'NinjaApiSheets_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.GetSheets)
  })
_sym_db.RegisterMessage(GetSheets)

Sheet = _reflection.GeneratedProtocolMessageType('Sheet', (_message.Message,), {
  'DESCRIPTOR' : _SHEET,
  '__module__' : 'NinjaApiSheets_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.Sheet)
  })
_sym_db.RegisterMessage(Sheet)

Sheets = _reflection.GeneratedProtocolMessageType('Sheets', (_message.Message,), {
  'DESCRIPTOR' : _SHEETS,
  '__module__' : 'NinjaApiSheets_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.Sheets)
  })
_sym_db.RegisterMessage(Sheets)

GetSheetRisk = _reflection.GeneratedProtocolMessageType('GetSheetRisk', (_message.Message,), {
  'DESCRIPTOR' : _GETSHEETRISK,
  '__module__' : 'NinjaApiSheets_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.GetSheetRisk)
  })
_sym_db.RegisterMessage(GetSheetRisk)

SheetRisk = _reflection.GeneratedProtocolMessageType('SheetRisk', (_message.Message,), {
  'DESCRIPTOR' : _SHEETRISK,
  '__module__' : 'NinjaApiSheets_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.SheetRisk)
  })
_sym_db.RegisterMessage(SheetRisk)

SheetRiskList = _reflection.GeneratedProtocolMessageType('SheetRiskList', (_message.Message,), {
  'DESCRIPTOR' : _SHEETRISKLIST,
  '__module__' : 'NinjaApiSheets_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.SheetRiskList)
  })
_sym_db.RegisterMessage(SheetRiskList)

GetSheetStates = _reflection.GeneratedProtocolMessageType('GetSheetStates', (_message.Message,), {
  'DESCRIPTOR' : _GETSHEETSTATES,
  '__module__' : 'NinjaApiSheets_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.GetSheetStates)
  })
_sym_db.RegisterMessage(GetSheetStates)

SheetState = _reflection.GeneratedProtocolMessageType('SheetState', (_message.Message,), {
  'DESCRIPTOR' : _SHEETSTATE,
  '__module__' : 'NinjaApiSheets_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.SheetState)
  })
_sym_db.RegisterMessage(SheetState)

SheetStates = _reflection.GeneratedProtocolMessageType('SheetStates', (_message.Message,), {
  'DESCRIPTOR' : _SHEETSTATES,
  '__module__' : 'NinjaApiSheets_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.SheetStates)
  })
_sym_db.RegisterMessage(SheetStates)


# @@protoc_insertion_point(module_scope)
