# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NinjaApiCommon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NinjaApiCommon.proto',
  package='NinjaApiMessages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14NinjaApiCommon.proto\x12\x10NinjaApiMessages\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\r\x12\r\n\x05month\x18\x02 \x01(\r\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\r\"(\n\x14\x44urationMilliseconds\x12\x10\n\x08\x64uration\x18\x01 \x01(\r\"%\n\x10\x45pochNanoseconds\x12\x11\n\ttimestamp\x18\x01 \x01(\x06*\x9e\x01\n\x08\x45xchange\x12\x14\n\x10UNKNOWN_EXCHANGE\x10\x00\x12\x07\n\x03\x43ME\x10\x01\x12\x07\n\x03ICE\x10\x02\x12\t\n\x05\x45NDEX\x10\x03\x12\t\n\x05LIFFE\x10\x04\x12\x07\n\x03\x43\x46\x45\x10\x05\x12\t\n\x05\x45UREX\x10\x06\x12\x07\n\x03LME\x10\x07\x12\x06\n\x02\x42\x33\x10\x08\x12\x07\n\x03JPX\x10\t\x12\x0b\n\x07\x46MX_FUT\x10\n\x12\x0b\n\x07\x46MX_UST\x10\x0b\x12\x0c\n\x08TRAYPORT\x10\x0c*+\n\x04Side\x12\x10\n\x0cUNKNOWN_SIDE\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02*K\n\tAggressor\x12\x15\n\x11UNKNOWN_AGGRESSOR\x10\x00\x12\t\n\x05\x42UYER\x10\x01\x12\n\n\x06SELLER\x10\x02\x12\x10\n\x0cNO_AGGRESSOR\x10\x03*Y\n\x0fMarketTradeType\x12\x11\n\rREGULAR_TRADE\x10\x00\x12\x11\n\rOPENING_TRADE\x10\x01\x12\x0f\n\x0b\x42LOCK_TRADE\x10\x02\x12\x0f\n\x0bOTHER_TRADE\x10\x03\x62\x06proto3'
)

_EXCHANGE = _descriptor.EnumDescriptor(
  name='Exchange',
  full_name='NinjaApiMessages.Exchange',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_EXCHANGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CME', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ICE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENDEX', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIFFE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CFE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EUREX', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LME', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='B3', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JPX', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FMX_FUT', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FMX_UST', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRAYPORT', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=174,
  serialized_end=332,
)
_sym_db.RegisterEnumDescriptor(_EXCHANGE)

Exchange = enum_type_wrapper.EnumTypeWrapper(_EXCHANGE)
_SIDE = _descriptor.EnumDescriptor(
  name='Side',
  full_name='NinjaApiMessages.Side',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_SIDE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=334,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_SIDE)

Side = enum_type_wrapper.EnumTypeWrapper(_SIDE)
_AGGRESSOR = _descriptor.EnumDescriptor(
  name='Aggressor',
  full_name='NinjaApiMessages.Aggressor',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_AGGRESSOR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUYER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELLER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NO_AGGRESSOR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=379,
  serialized_end=454,
)
_sym_db.RegisterEnumDescriptor(_AGGRESSOR)

Aggressor = enum_type_wrapper.EnumTypeWrapper(_AGGRESSOR)
_MARKETTRADETYPE = _descriptor.EnumDescriptor(
  name='MarketTradeType',
  full_name='NinjaApiMessages.MarketTradeType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REGULAR_TRADE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPENING_TRADE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_TRADE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTHER_TRADE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=456,
  serialized_end=545,
)
_sym_db.RegisterEnumDescriptor(_MARKETTRADETYPE)

MarketTradeType = enum_type_wrapper.EnumTypeWrapper(_MARKETTRADETYPE)
UNKNOWN_EXCHANGE = 0
CME = 1
ICE = 2
ENDEX = 3
LIFFE = 4
CFE = 5
EUREX = 6
LME = 7
B3 = 8
JPX = 9
FMX_FUT = 10
FMX_UST = 11
TRAYPORT = 12
UNKNOWN_SIDE = 0
BUY = 1
SELL = 2
UNKNOWN_AGGRESSOR = 0
BUYER = 1
SELLER = 2
NO_AGGRESSOR = 3
REGULAR_TRADE = 0
OPENING_TRADE = 1
BLOCK_TRADE = 2
OTHER_TRADE = 3



_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='NinjaApiMessages.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='NinjaApiMessages.Date.year', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='month', full_name='NinjaApiMessages.Date.month', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='day', full_name='NinjaApiMessages.Date.day', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=90,
)


_DURATIONMILLISECONDS = _descriptor.Descriptor(
  name='DurationMilliseconds',
  full_name='NinjaApiMessages.DurationMilliseconds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='NinjaApiMessages.DurationMilliseconds.duration', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=132,
)


_EPOCHNANOSECONDS = _descriptor.Descriptor(
  name='EpochNanoseconds',
  full_name='NinjaApiMessages.EpochNanoseconds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='NinjaApiMessages.EpochNanoseconds.timestamp', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=171,
)

DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['DurationMilliseconds'] = _DURATIONMILLISECONDS
DESCRIPTOR.message_types_by_name['EpochNanoseconds'] = _EPOCHNANOSECONDS
DESCRIPTOR.enum_types_by_name['Exchange'] = _EXCHANGE
DESCRIPTOR.enum_types_by_name['Side'] = _SIDE
DESCRIPTOR.enum_types_by_name['Aggressor'] = _AGGRESSOR
DESCRIPTOR.enum_types_by_name['MarketTradeType'] = _MARKETTRADETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'NinjaApiCommon_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.Date)
  })
_sym_db.RegisterMessage(Date)

DurationMilliseconds = _reflection.GeneratedProtocolMessageType('DurationMilliseconds', (_message.Message,), {
  'DESCRIPTOR' : _DURATIONMILLISECONDS,
  '__module__' : 'NinjaApiCommon_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.DurationMilliseconds)
  })
_sym_db.RegisterMessage(DurationMilliseconds)

EpochNanoseconds = _reflection.GeneratedProtocolMessageType('EpochNanoseconds', (_message.Message,), {
  'DESCRIPTOR' : _EPOCHNANOSECONDS,
  '__module__' : 'NinjaApiCommon_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.EpochNanoseconds)
  })
_sym_db.RegisterMessage(EpochNanoseconds)


# @@protoc_insertion_point(module_scope)
