# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NinjaApiWorkingRules.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NinjaApiWorkingRules.proto',
  package='NinjaApiMessages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aNinjaApiWorkingRules.proto\x12\x10NinjaApiMessages\"\xb2\x04\n\x0bWorkingRule\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\x38\n\x08workType\x18\x02 \x01(\x0e\x32&.NinjaApiMessages.WorkingRule.WorkType\"\xd8\x03\n\x08WorkType\x12\t\n\x05LIMIT\x10\x00\x12\r\n\tWORK_STOP\x10\x01\x12\x0e\n\nSTOP_LIMIT\x10\x02\x12\x10\n\x0cHBLA_RETIRED\x10\x03\x12\x0f\n\x0bOTHER_MONTH\x10\x04\x12\x0b\n\x07\x43\x41SCADE\x10\x05\x12\x0f\n\x0bSIZE_CUTOFF\x10\x06\x12\x0e\n\nSTERL_HBLA\x10\x07\x12\x0c\n\x08\x42OR_HBLA\x10\x08\x12\x0e\n\nLEAD_MONTH\x10\t\x12\r\n\tLEG_SPLIT\x10\n\x12\x13\n\x0f\x46\x41\x44\x45_STOP_LIMIT\x10\x0b\x12\x14\n\x10\x46\x41\x44\x45_SIZE_CUTOFF\x10\x0c\x12\x0e\n\nFADE_LIMIT\x10\r\x12\x0e\n\nSCO_SPREAD\x10\x0e\x12\x0e\n\nBEST_MONTH\x10\x0f\x12\x0f\n\x0bSMART_SPLIT\x10\x10\x12\x18\n\x14OUTRIGHT_SMART_SPLIT\x10\x11\x12\x0c\n\x08SCO_MINI\x10\x12\x12\x12\n\x0eOPTION_SCRATCH\x10\x13\x12\x0b\n\x07\x44YNAMIC\x10\x14\x12\x0e\n\nSTOP_PRICE\x10\x15\x12\r\n\tSOFR_HBLA\x10\x16\x12\x18\n\x14\x44YNAMIC_HEDGE_OFFSET\x10\x17\x12\t\n\x05\x45\x41GLE\x10\x18\x12\x0b\n\x07PARTIAL\x10\x19\x12\x0b\n\x07\x41GRO_EE\x10\x1a\x12\x11\n\rAGRO_PLUS_ONE\x10\x1b\"C\n\x0cWorkingRules\x12\x33\n\x0cworkingRules\x18\x01 \x03(\x0b\x32\x1d.NinjaApiMessages.WorkingRuleb\x06proto3'
)



_WORKINGRULE_WORKTYPE = _descriptor.EnumDescriptor(
  name='WorkType',
  full_name='NinjaApiMessages.WorkingRule.WorkType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIMIT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WORK_STOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP_LIMIT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HBLA_RETIRED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OTHER_MONTH', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CASCADE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SIZE_CUTOFF', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STERL_HBLA', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOR_HBLA', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEAD_MONTH', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEG_SPLIT', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FADE_STOP_LIMIT', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FADE_SIZE_CUTOFF', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FADE_LIMIT', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SCO_SPREAD', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BEST_MONTH', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SMART_SPLIT', index=16, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OUTRIGHT_SMART_SPLIT', index=17, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SCO_MINI', index=18, number=18,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPTION_SCRATCH', index=19, number=19,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DYNAMIC', index=20, number=20,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP_PRICE', index=21, number=21,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOFR_HBLA', index=22, number=22,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DYNAMIC_HEDGE_OFFSET', index=23, number=23,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EAGLE', index=24, number=24,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARTIAL', index=25, number=25,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AGRO_EE', index=26, number=26,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AGRO_PLUS_ONE', index=27, number=27,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=139,
  serialized_end=611,
)
_sym_db.RegisterEnumDescriptor(_WORKINGRULE_WORKTYPE)


_WORKINGRULE = _descriptor.Descriptor(
  name='WorkingRule',
  full_name='NinjaApiMessages.WorkingRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefix', full_name='NinjaApiMessages.WorkingRule.prefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workType', full_name='NinjaApiMessages.WorkingRule.workType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WORKINGRULE_WORKTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=611,
)


_WORKINGRULES = _descriptor.Descriptor(
  name='WorkingRules',
  full_name='NinjaApiMessages.WorkingRules',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workingRules', full_name='NinjaApiMessages.WorkingRules.workingRules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=680,
)

_WORKINGRULE.fields_by_name['workType'].enum_type = _WORKINGRULE_WORKTYPE
_WORKINGRULE_WORKTYPE.containing_type = _WORKINGRULE
_WORKINGRULES.fields_by_name['workingRules'].message_type = _WORKINGRULE
DESCRIPTOR.message_types_by_name['WorkingRule'] = _WORKINGRULE
DESCRIPTOR.message_types_by_name['WorkingRules'] = _WORKINGRULES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkingRule = _reflection.GeneratedProtocolMessageType('WorkingRule', (_message.Message,), {
  'DESCRIPTOR' : _WORKINGRULE,
  '__module__' : 'NinjaApiWorkingRules_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.WorkingRule)
  })
_sym_db.RegisterMessage(WorkingRule)

WorkingRules = _reflection.GeneratedProtocolMessageType('WorkingRules', (_message.Message,), {
  'DESCRIPTOR' : _WORKINGRULES,
  '__module__' : 'NinjaApiWorkingRules_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.WorkingRules)
  })
_sym_db.RegisterMessage(WorkingRules)


# @@protoc_insertion_point(module_scope)
