# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NinjaApiPositions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import NinjaApiCommon_pb2 as NinjaApiCommon__pb2
import NinjaApiContracts_pb2 as NinjaApiContracts__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='NinjaApiPositions.proto',
  package='NinjaApiMessages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17NinjaApiPositions.proto\x12\x10NinjaApiMessages\x1a\x14NinjaApiCommon.proto\x1a\x17NinjaApiContracts.proto\"b\n\x0cGetPositions\x12\x10\n\x08\x61\x63\x63ounts\x18\x01 \x03(\t\x12+\n\x07\x66ilters\x18\x02 \x03(\x0b\x32\x1a.NinjaApiMessages.Contract\x12\x13\n\x0bincludeSpec\x18\x03 \x01(\x08\"\xa9\x01\n\x08Position\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12,\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x1a.NinjaApiMessages.Contract\x12)\n\ttradeDate\x18\x03 \x01(\x0b\x32\x16.NinjaApiMessages.Date\x12\x10\n\x08\x64\x61ilyPos\x18\x04 \x01(\x05\x12\x0f\n\x07openPos\x18\x05 \x01(\x05\x12\x10\n\x08totalPos\x18\x06 \x01(\x05\":\n\tPositions\x12-\n\tpositions\x18\x01 \x03(\x0b\x32\x1a.NinjaApiMessages.Positionb\x06proto3'
  ,
  dependencies=[NinjaApiCommon__pb2.DESCRIPTOR,NinjaApiContracts__pb2.DESCRIPTOR,])




_GETPOSITIONS = _descriptor.Descriptor(
  name='GetPositions',
  full_name='NinjaApiMessages.GetPositions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accounts', full_name='NinjaApiMessages.GetPositions.accounts', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filters', full_name='NinjaApiMessages.GetPositions.filters', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='includeSpec', full_name='NinjaApiMessages.GetPositions.includeSpec', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=190,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='NinjaApiMessages.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='NinjaApiMessages.Position.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contract', full_name='NinjaApiMessages.Position.contract', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tradeDate', full_name='NinjaApiMessages.Position.tradeDate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dailyPos', full_name='NinjaApiMessages.Position.dailyPos', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='openPos', full_name='NinjaApiMessages.Position.openPos', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalPos', full_name='NinjaApiMessages.Position.totalPos', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=362,
)


_POSITIONS = _descriptor.Descriptor(
  name='Positions',
  full_name='NinjaApiMessages.Positions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='NinjaApiMessages.Positions.positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=422,
)

_GETPOSITIONS.fields_by_name['filters'].message_type = NinjaApiContracts__pb2._CONTRACT
_POSITION.fields_by_name['contract'].message_type = NinjaApiContracts__pb2._CONTRACT
_POSITION.fields_by_name['tradeDate'].message_type = NinjaApiCommon__pb2._DATE
_POSITIONS.fields_by_name['positions'].message_type = _POSITION
DESCRIPTOR.message_types_by_name['GetPositions'] = _GETPOSITIONS
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Positions'] = _POSITIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPositions = _reflection.GeneratedProtocolMessageType('GetPositions', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSITIONS,
  '__module__' : 'NinjaApiPositions_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.GetPositions)
  })
_sym_db.RegisterMessage(GetPositions)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'NinjaApiPositions_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.Position)
  })
_sym_db.RegisterMessage(Position)

Positions = _reflection.GeneratedProtocolMessageType('Positions', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONS,
  '__module__' : 'NinjaApiPositions_pb2'
  # @@protoc_insertion_point(class_scope:NinjaApiMessages.Positions)
  })
_sym_db.RegisterMessage(Positions)


# @@protoc_insertion_point(module_scope)
